// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/game-connect/gc-server/config/database"
	"github.com/game-connect/gc-server/infra/dao"
	"github.com/game-connect/gc-server/websocket/presentation/controller"
	"github.com/game-connect/gc-server/websocket/service"
)

// Injectors from wire.go:

// chat
func InitializeChatController() controller.ChatController {
	db := database.NewDB()
	chatRepository := dao.NewChatDao(db)
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	chatService := service.NewChatService(chatRepository, userRepository, transactionRepository)
	userService := service.NewUserService(userRepository, transactionRepository)
	chatController := controller.NewChatController(chatService, userService)
	return chatController
}

// channel_chat
func InitializeChannelChatController() controller.ChannelChatController {
	db := database.NewDB()
	channelChatRepository := dao.NewChannelChatDao(db)
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	channelChatService := service.NewChannelChatService(channelChatRepository, userRepository, transactionRepository)
	userService := service.NewUserService(userRepository, transactionRepository)
	channelChatController := controller.NewChannelChatController(channelChatService, userService)
	return channelChatController
}

// open_chat
func InitializeOpenChatController() controller.OpenChatController {
	db := database.NewDB()
	openChatRepository := dao.NewOpenChatDao(db)
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	openChatService := service.NewOpenChatService(openChatRepository, userRepository, transactionRepository)
	userService := service.NewUserService(userRepository, transactionRepository)
	openChatController := controller.NewOpenChatController(openChatService, userService)
	return openChatController
}

// room_chat
func InitializeRoomChatController() controller.RoomChatController {
	db := database.NewDB()
	roomChatRepository := dao.NewRoomChatDao(db)
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	roomChatService := service.NewRoomChatService(roomChatRepository, userRepository, transactionRepository)
	userService := service.NewUserService(userRepository, transactionRepository)
	roomChatController := controller.NewRoomChatController(roomChatService, userService)
	return roomChatController
}
