// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/game-connect/gc-server/config/database"
	"github.com/game-connect/gc-server/infra/dao"
	"github.com/game-connect/gc-server/websocket/presentation/controller"
	"github.com/game-connect/gc-server/websocket/presentation/middleware"
	"github.com/game-connect/gc-server/websocket/service"
)

// Injectors from wire.go:

// chat
func InitializeChatController() controller.ChatController {
	db := database.NewDB()
	chatRepository := dao.NewChatDao(db)
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	chatService := service.NewChatService(chatRepository, userRepository, transactionRepository)
	userService := service.NewUserService(userRepository, transactionRepository)
	chatController := controller.NewChatController(chatService, userService)
	return chatController
}

// user
func InitializeUserMiddleware() middleware.UserMiddleware {
	db := database.NewDB()
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	userService := service.NewUserService(userRepository, transactionRepository)
	userMiddleware := middleware.NewUserMiddleware(userService)
	return userMiddleware
}
