version: '3'
services:
# API
  api:
    build: 
      target: ${APP_ENV}
      context: ./
    volumes:
      - ./:/go/src/app
    ports:
      - "8001:8000"
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

# Swagger mock
  swagger:
    build:
      target: ${APP_ENV}
      context: ./swagger
    volumes:
      - .:/swagger:cached
    ports:
      - "8002:8000"
    tty: true
