version: '3'
services:
  app:
    build:
      target: ${APP_ENV}
    volumes:
      - ./:/go/src/app
    ports:
      - "8001:8000"
    tty: true
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
