// Package swagger GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/channel/{userKey}/channel_create/{roomKey}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "チャンネル作成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CreateChannel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/channel/{userKey}/channel_delete/{channelKey}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "チャンネル削除",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.DeleteChannel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/channel/{userKey}/channel_list/{roomKey}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Channel"
                ],
                "summary": "チャンネル一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListChannel"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/chat_create/{channelKey}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "チャット作成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CreateChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/chat_list/{channelKey}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "チャット一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/create_channel_chat/{channelKey}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChannelChat"
                ],
                "summary": "チャット作成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CreateChannelChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/create_open_chat/{channelKey}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenChat"
                ],
                "summary": "チャット作成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CreateOpenChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/create_room_chat/{roomKey}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomChat"
                ],
                "summary": "チャット作成",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CreateRoomChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/list_channel_chat/{channelKey}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ChannelChat"
                ],
                "summary": "チャット一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListChannelChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/list_croom_chat/{roomKey}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoomChat"
                ],
                "summary": "チャット一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListRoomChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/chat/{userKey}/list_open_chat": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "OpenChat"
                ],
                "summary": "チャット一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListOpenChat"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/genre/list_genre": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genre"
                ],
                "summary": "ジャンル一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListGenre"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/room/{userKey}/room_join/{roomKey}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "ルーム参加",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.JoinRoom"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/room/{userKey}/room_list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "ルーム一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListRoom"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/room/{userKey}/room_out/{roomKey}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "ルーム退出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.OutRoom"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/room/{user_key}/room_delete/{roomKey}": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "ルーム削除",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.DeleteRoom"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/{user_key}/room_create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Room"
                ],
                "summary": "ルーム作成",
                "parameters": [
                    {
                        "description": "ルーム作成",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameter.CreateRoom"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CreateRoom"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "output.CreateChannel": {
            "type": "object",
            "properties": {
                "channel_key": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "room_key": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "output.CreateChannelChat": {
            "type": "object",
            "properties": {
                "channel_chat_key": {
                    "type": "string"
                },
                "channel_key": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                }
            }
        },
        "output.CreateChat": {
            "type": "object",
            "properties": {
                "channel_key": {
                    "type": "string"
                },
                "chat_key": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                }
            }
        },
        "output.CreateOpenChat": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "open_chat_key": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                }
            }
        },
        "output.CreateRoom": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "room_key": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_count": {
                    "type": "integer"
                }
            }
        },
        "output.CreateRoomChat": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "room_chat_key": {
                    "type": "string"
                },
                "room_key": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                }
            }
        },
        "output.DeleteChannel": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "output.DeleteRoom": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "output.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "output.JoinRoom": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "room_user_key": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "output.ListChannel": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListChannelContent"
                    }
                },
                "message": {
                    "type": "string"
                },
                "room_key": {
                    "type": "string"
                }
            }
        },
        "output.ListChannelChat": {
            "type": "object",
            "properties": {
                "channel_key": {
                    "type": "string"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListChannelChatContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListChannelChatContent": {
            "type": "object",
            "properties": {
                "channel_chat_key": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "output.ListChannelContent": {
            "type": "object",
            "properties": {
                "channel_key": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "output.ListChat": {
            "type": "object",
            "properties": {
                "channel_key": {
                    "type": "string"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListChatContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListChatContent": {
            "type": "object",
            "properties": {
                "chat_key": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "output.ListGenre": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListGenreContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListGenreContent": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "genre_key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "output.ListOpenChat": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListOpenChatContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListOpenChatContent": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "open_chat_key": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "output.ListRoom": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListRoomContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListRoomChat": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListRoomChatContent"
                    }
                },
                "message": {
                    "type": "string"
                },
                "room_key": {
                    "type": "string"
                }
            }
        },
        "output.ListRoomChatContent": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "posted_at": {
                    "type": "string"
                },
                "room_chat_key": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                },
                "user_name": {
                    "type": "string"
                }
            }
        },
        "output.ListRoomContent": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "room_key": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "output.OutRoom": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "parameter.CreateRoom": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "items": {},
                "status": {
                    "type": "integer"
                },
                "types": {
                    "type": "string"
                }
            }
        },
        "response.Success": {
            "type": "object",
            "properties": {
                "items": {},
                "status": {
                    "type": "integer"
                },
                "types": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Chat Connect",
	Description:      "This is a sample swagger server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
