basePath: /
definitions:
  output.ChannelCreate:
    properties:
      channel_key:
        type: string
      explanation:
        type: string
      message:
        type: string
      name:
        type: string
      room_key:
        type: string
      type:
        type: string
    type: object
  output.ChannelList:
    properties:
      list:
        items:
          $ref: '#/definitions/output.ChannelListContent'
        type: array
      message:
        type: string
      room_key:
        type: string
    type: object
  output.ChannelListContent:
    properties:
      channel_key:
        type: string
      explanation:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  output.ChatCreate:
    properties:
      channel_key:
        type: string
      chat_key:
        type: string
      content:
        type: string
      message:
        type: string
      user_key:
        type: string
    type: object
  output.ChatList:
    properties:
      channel_key:
        type: string
      list:
        items:
          $ref: '#/definitions/output.ChatListContent'
        type: array
      message:
        type: string
    type: object
  output.ChatListContent:
    properties:
      chat_key:
        type: string
      content:
        type: string
      user_key:
        type: string
      user_name:
        type: string
    type: object
  output.Error:
    properties:
      message:
        type: string
    type: object
  output.RoomCreate:
    properties:
      explanation:
        type: string
      image_path:
        type: string
      message:
        type: string
      name:
        type: string
      room_key:
        type: string
      status:
        type: string
      user_count:
        type: integer
    type: object
  output.RoomJoin:
    properties:
      message:
        type: string
      room_user_key:
        type: string
      status:
        type: string
    type: object
  output.RoomOut:
    properties:
      message:
        type: string
    type: object
  output.UserCheck:
    properties:
      email:
        type: string
      message:
        type: string
      name:
        type: string
      user_key:
        type: string
    type: object
  output.UserDelete:
    properties:
      message:
        type: string
    type: object
  output.UserLogin:
    properties:
      email:
        type: string
      message:
        type: string
      name:
        type: string
      token:
        type: string
      user_key:
        type: string
    type: object
  output.UserLogout:
    properties:
      message:
        type: string
    type: object
  output.UserRegister:
    properties:
      email:
        type: string
      message:
        type: string
      name:
        type: string
      user_key:
        type: string
    type: object
  parameter.RoomCreate:
    properties:
      explanation:
        type: string
      name:
        type: string
    type: object
  parameter.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  parameter.UserRegister:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  response.Error:
    properties:
      items: {}
      status:
        type: integer
      types:
        type: string
    type: object
  response.Success:
    properties:
      items: {}
      status:
        type: integer
      types:
        type: string
    type: object
host: localhost:8001
info:
  contact: {}
  description: This is a sample swagger server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Chat Connect
  version: "1.0"
paths:
  /auth/user_check/{user_key}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: user_key
        in: path
        maxLength: 12
        name: user_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.UserCheck'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      security:
      - ApiKeyAuth: []
      summary: ユーザー取得
      tags:
      - User
  /auth/user_delete/{user_key}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: ユーザーキー
        in: path
        name: user_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.UserDelete'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      security:
      - ApiKeyAuth: []
      summary: ユーザー削除
      tags:
      - User
  /auth/user_login:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザーログイン
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.UserLogin'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: ユーザーログイン
      tags:
      - Auth
  /auth/user_logout/{user_key}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: user_key
        in: path
        maxLength: 12
        name: user_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.UserLogout'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      security:
      - ApiKeyAuth: []
      summary: ログアウト
      tags:
      - User
  /auth/user_register:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー登録
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.UserRegister'
              type: object
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/output.Error'
            type: array
      summary: ユーザー登録
      tags:
      - Auth
  /channel/{userKey}/channel_create/{roomKey}:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.ChannelCreate'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: チャンネル作成
      tags:
      - Channel
  /channel/{userKey}/channel_list/{roomKey}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.ChannelList'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: チャンネル一覧取得
      tags:
      - Channel
  /chat/{userKey}/chat_create/{channelKey}:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.ChatCreate'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: チャット作成
      tags:
      - Chat
  /chat/{userKey}/chat_list/{channelKey}:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.ChatList'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: チャット一覧取得
      tags:
      - Chat
  /room/{userKey}/room_join/{roomKey}:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.RoomJoin'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: ルーム参加
      tags:
      - Room
  /room/{userKey}/room_out/{roomKey}:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.RoomOut'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: ルーム退出
      tags:
      - Room
  /user/{user_key}/room_create:
    post:
      consumes:
      - application/json
      parameters:
      - description: ルーム作成
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.RoomCreate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                items:
                  $ref: '#/definitions/output.RoomCreate'
              type: object
        "500":
          description: Internal Server Error
          schema:
            allOf:
            - $ref: '#/definitions/response.Error'
            - properties:
                errors:
                  $ref: '#/definitions/output.Error'
              type: object
      summary: ルーム作成
      tags:
      - Room
swagger: "2.0"
