basePath: /
definitions:
  output.Error:
    properties:
      message:
        type: string
    type: object
  output.UserCheck:
    properties:
      email:
        type: string
      message:
        type: string
      name:
        type: string
      user_key:
        type: string
    type: object
  output.UserDelete:
    properties:
      message:
        type: string
    type: object
  output.UserLogin:
    properties:
      email:
        type: string
      message:
        type: string
      name:
        type: string
      token:
        type: string
      user_key:
        type: string
    type: object
  output.UserLogout:
    properties:
      message:
        type: string
    type: object
  output.UserRegister:
    properties:
      email:
        type: string
      message:
        type: string
      name:
        type: string
      user_key:
        type: string
    type: object
  parameter.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  parameter.UserRegister:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  response.Success:
    properties:
      items: {}
      status:
        type: integer
      types:
        type: string
    type: object
host: localhost:8001
info:
  contact: {}
  description: This is a sample swagger server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Chat Connect
  version: "1.0"
paths:
  /auth/user_login:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザーログイン
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                Items:
                  $ref: '#/definitions/output.UserLogin'
              type: object
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/output.Error'
            type: array
      summary: ユーザーログイン
      tags:
      - Auth
  /auth/user_register:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー登録
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                Items:
                  $ref: '#/definitions/output.UserRegister'
              type: object
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/output.Error'
            type: array
      summary: ユーザー登録
      tags:
      - Auth
  /user/{user_key}/user_check:
    get:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: user_key
        in: path
        maxLength: 12
        name: user_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                Items:
                  $ref: '#/definitions/output.UserCheck'
              type: object
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/output.Error'
            type: array
      security:
      - ApiKeyAuth: []
      summary: ユーザー取得
      tags:
      - User
  /user/{user_key}/user_delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: ユーザーキー
        in: path
        name: user_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                Items:
                  $ref: '#/definitions/output.UserDelete'
              type: object
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/output.Error'
            type: array
      security:
      - ApiKeyAuth: []
      summary: ユーザー削除
      tags:
      - User
  /user/{user_key}/user_logout:
    put:
      consumes:
      - application/json
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: user_key
        in: path
        maxLength: 12
        name: user_key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Success'
            - properties:
                Items:
                  $ref: '#/definitions/output.UserLogout'
              type: object
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/output.Error'
            type: array
      security:
      - ApiKeyAuth: []
      summary: ログアウト
      tags:
      - User
swagger: "2.0"
