// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/game-connect/gc-server/auth/presentation/controller"
	"github.com/game-connect/gc-server/auth/presentation/middleware"
	"github.com/game-connect/gc-server/auth/service"
	"github.com/game-connect/gc-server/config/database"
	"github.com/game-connect/gc-server/infra/dao"
)

// Injectors from wire.go:

// user
func InitializeUserController() controller.UserController {
	db := database.NewDB()
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	userService := service.NewUserService(userRepository, transactionRepository)
	userController := controller.NewUserController(userService)
	return userController
}

// user
func InitializeUserMiddleware() middleware.UserMiddleware {
	db := database.NewDB()
	userRepository := dao.NewUserDao(db)
	transactionRepository := dao.NewTransactionDao(db)
	userService := service.NewUserService(userRepository, transactionRepository)
	userMiddleware := middleware.NewUserMiddleware(userService)
	return userMiddleware
}
