// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/game-connect/gc-server/batch/command"
	"github.com/game-connect/gc-server/batch/service"
	"github.com/game-connect/gc-server/config/database"
	"github.com/game-connect/gc-server/infra/dao"
)

// Injectors from wire.go:

// user
func InitializeUserCommand() command.UserCommand {
	db := database.NewDB()
	userRepository := dao.NewUserDao(db)
	userService := service.NewUserService(userRepository)
	userCommand := command.NewUserCommand(userService)
	return userCommand
}
