// Package game GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package game

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/check_admin_user/{admin_user_key}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "企業ユーザー取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "maxLength": 12,
                        "type": "string",
                        "description": "user_key",
                        "name": "user_key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CheckAdminUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/delete_admin_user/{admin_user_key}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ユーザー削除",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ユーザーキー",
                        "name": "user_key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.DeleteAdminUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/login_admin_user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "企業ユーザーログイン",
                "parameters": [
                    {
                        "description": "企業ユーザーログイン",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameter.LoginUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.LoginAdminUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/user_admin_register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "企業ユーザー登録",
                "parameters": [
                    {
                        "description": "企業ユーザー登録",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameter.RegisterAdminUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.RegisterAdminUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/output.Error"
                            }
                        }
                    }
                }
            }
        },
        "/auth/user_logout/{user_key}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ログアウト",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "maxLength": 12,
                        "type": "string",
                        "description": "user_key",
                        "name": "user_key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.LogoutAdminUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/game/{admin_user_key}/create_game": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LinkGame"
                ],
                "summary": "連携ゲーム作成",
                "parameters": [
                    {
                        "description": "連携ゲーム作成",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameter.CreateGame"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.CreateGame"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/game/{userKey}/list_game_user": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameUser"
                ],
                "summary": "連携ゲーム一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListGameUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/genre/list_game": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "ゲーム一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListGame"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/genre/list_genre": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Genre"
                ],
                "summary": "ジャンル＆ゲーム一覧取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListGenreAndGame"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/list_game_score": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameScore"
                ],
                "summary": "スコア更新",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.ListGameScore"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/login_user": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ユーザーログイン",
                "parameters": [
                    {
                        "description": "ユーザーログイン",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameter.LoginUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.LoginUser"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/update_game_score": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GameScore"
                ],
                "summary": "スコア更新",
                "parameters": [
                    {
                        "description": "スコア更新",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/parameter.UpdateGameScore"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Success"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "items": {
                                            "$ref": "#/definitions/output.UpdateGameScore"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Error"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "errors": {
                                            "$ref": "#/definitions/output.Error"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "output.CheckAdminUser": {
            "type": "object",
            "properties": {
                "admin_user_key": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "output.CreateGame": {
            "type": "object",
            "properties": {
                "admin_user_key": {
                    "type": "string"
                },
                "api_key": {
                    "type": "string"
                },
                "game_image_path": {
                    "type": "string"
                },
                "game_key": {
                    "type": "string"
                },
                "game_title": {
                    "type": "string"
                },
                "genre_key": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.DeleteAdminUser": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "output.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "output.GameSetting": {
            "type": "object",
            "properties": {
                "game_combo_score": {
                    "type": "boolean"
                },
                "game_play_time": {
                    "type": "boolean"
                },
                "game_rank": {
                    "type": "boolean"
                },
                "game_score": {
                    "type": "boolean"
                },
                "game_score_image_path": {
                    "type": "boolean"
                }
            }
        },
        "output.ListGame": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListGameContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListGameContent": {
            "type": "object",
            "properties": {
                "game_key": {
                    "type": "string"
                },
                "game_title": {
                    "type": "string"
                },
                "genre_key": {
                    "type": "string"
                }
            }
        },
        "output.ListGameScore": {
            "type": "object",
            "properties": {
                "game_image_path": {
                    "type": "string"
                },
                "game_key": {
                    "type": "string"
                },
                "game_title": {
                    "type": "string"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListGameScoreContent"
                    }
                },
                "message": {
                    "type": "string"
                },
                "setting": {
                    "$ref": "#/definitions/output.GameSetting"
                }
            }
        },
        "output.ListGameScoreContent": {
            "type": "object",
            "properties": {
                "game_combo_score": {
                    "type": "integer"
                },
                "game_play_time": {
                    "type": "integer"
                },
                "game_rank": {
                    "type": "integer"
                },
                "game_score": {
                    "type": "integer"
                },
                "game_score_image_path": {
                    "type": "string"
                }
            }
        },
        "output.ListGameUser": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListGameUserContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListGameUserContent": {
            "type": "object",
            "properties": {
                "game_image_path": {
                    "type": "string"
                },
                "game_key": {
                    "type": "string"
                },
                "game_title": {
                    "type": "string"
                }
            }
        },
        "output.ListGenre": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListGenreContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListGenreAndGame": {
            "type": "object",
            "properties": {
                "list_game": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListGameContent"
                    }
                },
                "list_genre": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/output.ListGenreContent"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "output.ListGenreContent": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "genre_key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "output.LoginAdminUser": {
            "type": "object",
            "properties": {
                "admin_user_key": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "output.LoginUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "image_path": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                }
            }
        },
        "output.LogoutAdminUser": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "output.RegisterAdminUser": {
            "type": "object",
            "properties": {
                "admin_user_key": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "output.UpdateGameScore": {
            "type": "object",
            "properties": {
                "game_combo_score": {
                    "type": "integer"
                },
                "game_key": {
                    "type": "string"
                },
                "game_play_time": {
                    "type": "integer"
                },
                "game_rank": {
                    "type": "integer"
                },
                "game_score": {
                    "type": "integer"
                },
                "game_score_image_path": {
                    "type": "string"
                },
                "user_key": {
                    "type": "string"
                }
            }
        },
        "parameter.CreateGame": {
            "type": "object",
            "properties": {
                "game_image": {
                    "type": "string"
                },
                "game_title": {
                    "type": "string"
                },
                "genre_key": {
                    "type": "string"
                },
                "setting": {
                    "type": "object",
                    "properties": {
                        "game_combo_score": {
                            "type": "boolean"
                        },
                        "game_play_time": {
                            "type": "boolean"
                        },
                        "game_rank": {
                            "type": "boolean"
                        },
                        "game_score": {
                            "type": "boolean"
                        },
                        "game_score_image": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "parameter.LoginUser": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "game_key": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "parameter.RegisterAdminUser": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "parameter.UpdateGameScore": {
            "type": "object",
            "properties": {
                "api_key": {
                    "type": "string"
                },
                "game_combo_score": {
                    "type": "integer"
                },
                "game_key": {
                    "type": "string"
                },
                "game_play_time": {
                    "type": "integer"
                },
                "game_rank": {
                    "type": "integer"
                },
                "game_score": {
                    "type": "integer"
                },
                "game_score_image": {
                    "type": "string"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "items": {},
                "status": {
                    "type": "integer"
                },
                "types": {
                    "type": "string"
                }
            }
        },
        "response.Success": {
            "type": "object",
            "properties": {
                "items": {},
                "status": {
                    "type": "integer"
                },
                "types": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8004",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Chat Connect",
	Description:      "This is a sample swagger server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
