basePath: /
definitions:
  output.Error:
    properties:
      message:
        type: string
    type: object
  output.UserRegister:
    properties:
      email:
        type: string
      message:
        type: string
      user_key:
        type: string
      username:
        type: string
    type: object
  parameter.UserRegister:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8001
info:
  contact: {}
  description: This is a sample swagger server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Chat Connect
  version: "1.0"
paths:
  /auth/user_register:
    post:
      consumes:
      - application/json
      parameters:
      - description: ユーザー登録
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/parameter.UserRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/output.UserRegister'
        "500":
          description: Internal Server Error
          schema:
            items:
              $ref: '#/definitions/output.Error'
            type: array
      summary: ユーザー登録
      tags:
      - Auth
swagger: "2.0"
