name: Go test

on:
  pull_request:
    branches:
      - main

jobs:
  model_test:
    name: Model test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run tests
        run: go test ./test/model_test/...

  dao_test:
    name: Dao test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run tests
        run: go test ./test/dao_test/...
  
  e2e_test:
    name: E2E test
    runs-on: ubuntu-latest
    env:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cc_server_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: 0.0.0.0:3306
      TEST_API_URL: http://0.0.0.0:8000
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: cc_server_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Start API
        run: go run api/main.go &

      - name: Sleep for 20 seconds
        run: sleep 20

      - name: Run tests
        run: go test ./test/e2e_test/...
