name: Go test

on:
  pull_request:
    branches:
      - main

jobs:
  model_test:
    name: Model test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run tests
      run: go test ./test/model_test/...

  dao_test:
    name: Dao test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Run tests
      run: go test ./test/dao_test/...

